$ANSIBLE_VAULT;1.1;AES256
62303565393863343334343430383333663165376366336164636135383930363964636639353331
6162376235653965663537353130353336623061313739360a373731393434323439303665343831
63656364303030633935653962623535663133326338346234316438366634383965613132326231
6664303431373135650a393834373564396438663134386532323166313163666132383265393633
65666263643865656632316261613630356135366435656539313364613164636163396634353837
64313364386630346636656434646635653964363861373364613661343062343135303334616333
66363563363933306461373637336538643539333435633438646137386537346364323462376163
34376666653233323963383737323264306635643165303431353738376565373433623434363530
38613633646337346232626534653637663435633564626363343330643162353733353137353831
31393864323435656339636265346132393737613632353035323161613531343835363637613138
39373666346166343831626136303630343531653134393564353033363037373662316331303564
36653864323937353636383135313532393463313633316663393066313838376532306239363137
36623161643262376431656263303265636230363530383264633864643633393337343561316632
39303166386264313030303963623661643636386233343839313436366638363632623466343437
35653739333230363931636636643230633963616333343862636538633031646331303662663735
65653432636236633263623037616536666333386161346364633861626261373136373239663636
36646239333535323533613232643036623037363365616539653937313933613164623336623231
66366637343861646338613831346438316362383335636439363164383839636436333266616638
37396532633864323263373934376566643239353965616563323634663062303266666361396230
34666530383163386664323339623564626232306163616330626433363439313633383331323338
31323234623661336636303161656662373333346638613632616432303465643563386537346461
36343937653530626362616236373631626562396133666632313138346665623661643734646564
31613233616130316666633566643432396538613339363737643034313061656338303030363966
34363439343430633937396161663537633866646530313137306363666532363936646639663463
64343730663936663536396432383033653435653063396232366630396430306333383165376233
6130313462626430656234326233393931386136383433383938
